package com.icastar.platform.dto.job;

import com.icastar.platform.entity.Job;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

@Data
public class JobFilterDto {
    
    // Search parameters
    private String searchTerm;
    private String jobTitle;
    private String companyName;
    
    // Filter parameters
    private Job.JobType jobType;
    private Job.ExperienceLevel experienceLevel;
    private Job.JobStatus status;
    
    // Pay range filters
    private BigDecimal minPay;
    private BigDecimal maxPay;
    private String currency;
    
    // Location filters
    private String location;
    private Boolean isRemote;
    
    // Additional filters
    private Boolean isUrgent;
    private Boolean isFeatured;
    private List<String> skills;
    private List<String> tags;
    
    // Pagination
    private Integer page = 0;
    private Integer size = 10;
    private String sortBy = "publishedAt";
    private String sortDirection = "desc";
    
    // Getters and setters are generated by Lombok @Data annotation
    
    // Manual setters to fix compilation issues
    public void setSearchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
    }
    
    public void setJobType(Job.JobType jobType) {
        this.jobType = jobType;
    }
    
    public void setExperienceLevel(Job.ExperienceLevel experienceLevel) {
        this.experienceLevel = experienceLevel;
    }
    
    public void setStatus(Job.JobStatus status) {
        this.status = status;
    }
    
    public void setMinPay(BigDecimal minPay) {
        this.minPay = minPay;
    }
    
    public void setMaxPay(BigDecimal maxPay) {
        this.maxPay = maxPay;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    public void setIsRemote(Boolean isRemote) {
        this.isRemote = isRemote;
    }
    
    public void setIsUrgent(Boolean isUrgent) {
        this.isUrgent = isUrgent;
    }
    
    public void setIsFeatured(Boolean isFeatured) {
        this.isFeatured = isFeatured;
    }
    
    public void setSkills(List<String> skills) {
        this.skills = skills;
    }
}
